# Generated by Django 5.2.1 on 2025-09-02 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_vaccinecampaign_is_premium_and_more'),
        ('payments', '0003_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('patient', 'campaign'), name='unique_patient_campaign_payment'),
        ),
    ]
