# Generated by Django 5.2.1 on 2025-09-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_unique_patient_campaign_payment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_patient_campaign_payment',
        ),
    ]
