# Generated by Django 5.2.1 on 2025-09-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_unique_patient_campaign_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
