# Generated by Django 5.2.1 on 2025-10-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_vaccinecampaign_banner'),
        ('payments', '0006_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('campaign', 'Campaign'), ('donation', 'Donation')], default='campaign', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='campaigns.vaccinecampaign'),
        ),
    ]
