# Generated by Django 5.2.1 on 2025-10-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_payment_type_alter_payment_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_donate',
            field=models.BooleanField(default=False),
        ),
    ]
