# Generated by Django 5.2.1 on 2025-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patientprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
