# Generated by Django 5.2.1 on 2025-08-24 14:17

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctorprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('certificate', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='doctor_certificates')),
                ('license_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_apply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
