# Generated by Django 5.2.1 on 2025-08-24 15:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctorapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorapplication',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='doctor_certificates'),
        ),
    ]
