# Generated by Django 5.2.1 on 2025-09-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_patientprofile_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-id']},
        ),
    ]
