# Generated by Django 5.2.1 on 2025-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdose',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Booked', max_length=20),
        ),
    ]
