# Generated by Django 5.2.1 on 2025-08-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
        ('campaigns', '0005_remove_vaccinecampaign_vaccine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdose',
            name='vaccine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_vaccine', to='campaigns.vaccine'),
            preserve_default=False,
        ),
    ]
