# Generated by Django 5.2.1 on 2025-08-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingdose_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdose',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('FirstCompleted', 'First Dose Completed'), ('SecondCompleted', 'Second Dose Completed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Booked', max_length=20),
        ),
    ]
