# Generated by Django 5.2.1 on 2025-08-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookingdose_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdose',
            name='booster_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
