# Generated by Django 5.2.1 on 2025-08-31 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingdose_booster_dose_date'),
        ('campaigns', '0005_remove_vaccinecampaign_vaccine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinationrecord',
            options={'ordering': ['given_date']},
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completed_vaccine', to='campaigns.vaccine'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='vaccinationrecord',
            constraint=models.UniqueConstraint(fields=('patient', 'campaign', 'vaccine', 'dose_number'), name='unique_vaccination_record'),
        ),
    ]
