# Generated by Django 5.2.1 on 2025-08-25 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinecampaign',
            name='doctor',
        ),
        migrations.AddField(
            model_name='vaccinecampaign',
            name='doctor',
            field=models.ManyToManyField(limit_choices_to={'role': 'Doctor'}, related_name='involve_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
