# Generated by Django 5.2.1 on 2025-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
