# Generated by Django 5.2.1 on 2025-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_vaccinecampaign_doctor_vaccinecampaign_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='booster_gap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='is_booster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='max_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='min_age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
