# Generated by Django 5.2.1 on 2025-06-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_vaccine_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinecampaign',
            options={'ordering': ['-id']},
        ),
    ]
