# Generated by Django 5.2.1 on 2025-08-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_vaccine_approved_date_vaccine_booster_gap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinecampaign',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='vaccinecampaign',
            name='vaccine',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='campaigns', to='campaigns.vaccine'),
        ),
    ]
