# Generated by Django 5.2.1 on 2025-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_vaccinecampaign_vaccine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaign',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinecampaign',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
