# Generated by Django 5.2.1 on 2025-09-04 04:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_vaccinecampaign_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaign',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='campaign_banner'),
        ),
    ]
